version: '3'
services:
  mqtt2db:
    build: mqtt2db/.
  mosqiuitto:
    image: eclipse-mosquitto
    ports:
     - "9001:9001"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
  adminer:
    image: adminer
    ports:
      - 8080:8080
  restifydb:
    build: restifydb/.
    ports:
      - 8090:80
